<?php
/**
 * @link https://github.com/thinker-g/yii2-hermes-mailing
 * @copyright Copyright (c) Thinker_g (Jiyan.guo@gmail.com)
 * @license MIT
 * @version v1.0.0
 * @author Thinker_g
 */
namespace thinkerg\HermesMailing;

use Yii;
use yii\base\BootstrapInterface;

class Module extends \yii\base\Module implements BootstrapInterface
{

    const EVENT_UNKNOWN_APP = 'hermesUnknownApp';



    /**
     * @inheritdoc
     */
    public $controllerNamespace = 'thinkerg\HermesMailing\controllers';

    /**
     * @inheritdoc
     */
    public $defaultRoute = 'mail/index';

    /**
     * Email AR model name.
     * Make sure the model class is imported after installation.
     * LEAVE THIS NULL, unless the model name is not generated by the table name.
     * If this is set, table name will be retrieved by "tableName()" of its instance.
     * This is for using some already existed AR. Won't be needed for default installation.
     * @var string
     */
    public $modelClass = 'app\\models\\HermesMail';
    
    /**
     * @override
     * @param \yii\base\Application $app
     */
    public function bootstrap($app)
    {
        
        if ($app instanceof \yii\web\Application) {

        } elseif ($app instanceof \yii\base\Application) {
            
        } else {
            $this->trigger(static::EVENT_UNKNOWN_APP);
        }
    }



     
}

?>
